# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_sync_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SyncFunctionsPanel(object):
    def setupUi(self, SyncFunctionsPanel):
        SyncFunctionsPanel.setObjectName("SyncFunctionsPanel")
        SyncFunctionsPanel.resize(800, 600)
        SyncFunctionsPanel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SyncFunctionsPanel.setWindowIcon(icon)
        SyncFunctionsPanel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(SyncFunctionsPanel)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(8, 10, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description = QtWidgets.QLabel(SyncFunctionsPanel)
        self.description.setTextFormat(QtCore.Qt.RichText)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.groupBox = QtWidgets.QGroupBox(SyncFunctionsPanel)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.vboxlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout.setContentsMargins(2, 2, 2, 2)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setObjectName("vboxlayout")
        self.functionsList = QtWidgets.QTableView(self.groupBox)
        self.functionsList.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.functionsList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.functionsList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.functionsList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.functionsList.setShowGrid(True)
        self.functionsList.setGridStyle(QtCore.Qt.SolidLine)
        self.functionsList.setSortingEnabled(False)
        self.functionsList.setWordWrap(False)
        self.functionsList.setCornerButtonEnabled(False)
        self.functionsList.setObjectName("functionsList")
        self.functionsList.horizontalHeader().setHighlightSections(False)
        self.functionsList.horizontalHeader().setMinimumSectionSize(20)
        self.functionsList.horizontalHeader().setStretchLastSection(True)
        self.functionsList.verticalHeader().setVisible(False)
        self.functionsList.verticalHeader().setHighlightSections(False)
        self.functionsList.verticalHeader().setMinimumSectionSize(20)
        self.vboxlayout.addWidget(self.functionsList)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.applyButton = QtWidgets.QPushButton(SyncFunctionsPanel)
        self.applyButton.setMinimumSize(QtCore.QSize(100, 0))
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.cancelButton = QtWidgets.QPushButton(SyncFunctionsPanel)
        self.cancelButton.setEnabled(True)
        self.cancelButton.setMinimumSize(QtCore.QSize(100, 0))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SyncFunctionsPanel)
        QtCore.QMetaObject.connectSlotsByName(SyncFunctionsPanel)

    def retranslateUi(self, SyncFunctionsPanel):
        _translate = QtCore.QCoreApplication.translate
        SyncFunctionsPanel.setWindowTitle(_translate("SyncFunctionsPanel", "RevEng.AI Toolkit: Sync Functions"))
        self.applyButton.setText(_translate("SyncFunctionsPanel", "&S&ync"))
        self.cancelButton.setText(_translate("SyncFunctionsPanel", "&C&ancel"))
