# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_analysis_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtGui
from PyQt5 import QtCore
from PyQt5 import QtWidgets

from revengai.gui.custom_flow_layout import CustomFlowLayout
from revengai.gui.slider import Slider


class Ui_AutoAnalysisPanel(object):
    def setupUi(self, AutoAnalysisPanel):
        AutoAnalysisPanel.setObjectName("AutoAnalysisPanel")
        AutoAnalysisPanel.resize(800, 600)
        AutoAnalysisPanel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/favicon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AutoAnalysisPanel.setWindowIcon(icon)
        AutoAnalysisPanel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(AutoAnalysisPanel)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(8, 10, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(AutoAnalysisPanel)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.tab)
        self.vboxlayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout.setContentsMargins(2, 2, 2, 2)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setObjectName("vboxlayout")
        self.central_widget = QtWidgets.QWidget()
        self.layoutFilter = CustomFlowLayout(parent=self.central_widget)
        self.layoutFilter.setObjectName("layoutFilter")
        self.central_widget.setLayout(self.layoutFilter)
        self.vboxlayout.addWidget(self.central_widget)
        self.collectionsFilter = QtWidgets.QLineEdit(self.tab)
        self.collectionsFilter.setClearButtonEnabled(True)
        self.collectionsFilter.setObjectName("collectionsFilter")
        self.vboxlayout.addWidget(self.collectionsFilter)
        self.collectionsTable = QtWidgets.QTableView(self.tab)
        self.collectionsTable.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.collectionsTable.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.collectionsTable.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.collectionsTable.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.collectionsTable.setShowGrid(True)
        self.collectionsTable.setGridStyle(QtCore.Qt.SolidLine)
        self.collectionsTable.setSortingEnabled(False)
        self.collectionsTable.setWordWrap(False)
        self.collectionsTable.setCornerButtonEnabled(False)
        self.collectionsTable.setObjectName("collectionsTable")
        self.collectionsTable.horizontalHeader().setHighlightSections(False)
        self.collectionsTable.horizontalHeader().setMinimumSectionSize(20)
        self.collectionsTable.horizontalHeader().setStretchLastSection(True)
        self.collectionsTable.verticalHeader().setVisible(False)
        self.collectionsTable.verticalHeader().setHighlightSections(False)
        self.collectionsTable.verticalHeader().setMinimumSectionSize(20)
        self.vboxlayout.addWidget(self.collectionsTable)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.tab_2)
        self.vboxlayout1.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout1.setContentsMargins(2, 2, 2, 2)
        self.vboxlayout1.setSpacing(4)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.resultsFilter = QtWidgets.QLineEdit(self.tab_2)
        self.resultsFilter.setClearButtonEnabled(True)
        self.resultsFilter.setObjectName("resultsFilter")
        self.vboxlayout1.addWidget(self.resultsFilter)
        self.resultsTable = QtWidgets.QTableView(self.tab_2)
        self.resultsTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.resultsTable.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultsTable.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.resultsTable.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.resultsTable.setShowGrid(True)
        self.resultsTable.setGridStyle(QtCore.Qt.SolidLine)
        self.resultsTable.setSortingEnabled(False)
        self.resultsTable.setWordWrap(False)
        self.resultsTable.setCornerButtonEnabled(False)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.horizontalHeader().setHighlightSections(False)
        self.resultsTable.horizontalHeader().setMinimumSectionSize(20)
        self.resultsTable.horizontalHeader().setStretchLastSection(True)
        self.resultsTable.verticalHeader().setVisible(False)
        self.resultsTable.verticalHeader().setHighlightSections(False)
        self.resultsTable.verticalHeader().setMinimumSectionSize(20)
        self.vboxlayout1.addWidget(self.resultsTable)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.description = QtWidgets.QLabel(AutoAnalysisPanel)
        self.description.setTextFormat(QtCore.Qt.RichText)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.confidenceSlider = Slider(AutoAnalysisPanel)
        self.confidenceSlider.setMaximum(100)
        self.confidenceSlider.setPageStep(5)
        self.confidenceSlider.setSliderPosition(90)
        self.confidenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confidenceSlider.setInvertedAppearance(False)
        self.confidenceSlider.setInvertedControls(False)
        self.confidenceSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.confidenceSlider.setTickInterval(5)
        self.confidenceSlider.setObjectName("confidenceSlider")
        self.verticalLayout.addWidget(self.confidenceSlider)
        self.progressBar = QtWidgets.QProgressBar(AutoAnalysisPanel)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.fetchButton = QtWidgets.QPushButton(AutoAnalysisPanel)
        self.fetchButton.setObjectName("fetchButton")
        self.horizontalLayout.addWidget(self.fetchButton)
        self.renameButton = QtWidgets.QPushButton(AutoAnalysisPanel)
        self.renameButton.setEnabled(False)
        self.renameButton.setObjectName("renameButton")
        self.horizontalLayout.addWidget(self.renameButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AutoAnalysisPanel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AutoAnalysisPanel)

    def retranslateUi(self, AutoAnalysisPanel):
        _translate = QtCore.QCoreApplication.translate
        AutoAnalysisPanel.setWindowTitle(_translate(
            "AutoAnalysisPanel", "RevEng.AI Toolkit: Auto Analysis"))
        self.collectionsFilter.setPlaceholderText(
            _translate("AutoAnalysisPanel", "Search Collections…"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("AutoAnalysisPanel", "Collections"))
        self.resultsFilter.setPlaceholderText(
            _translate("AutoAnalysisPanel", "Filter Functions…"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("AutoAnalysisPanel", "Results"))
        self.fetchButton.setText(_translate(
            "AutoAnalysisPanel", "Fetch Results"))
        self.renameButton.setText(_translate("AutoAnalysisPanel", "Rename"))
